"""update field in table

Revision ID: 03a89ff58e5d
Revises: 93318747b557
Create Date: 2022-11-10 23:20:21.852023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03a89ff58e5d'
down_revision = '93318747b557'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes_results', sa.Column('gpa', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes_results', 'gpa')
    # ### end Alembic commands ###
