"""eighteenth migration created requests table

Revision ID: b8e61169c882
Revises: 462e812d00ee
Create Date: 2022-11-01 23:22:25.711311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e61169c882'
down_revision = '462e812d00ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
