"""update quizzes table

Revision ID: e2474a68e112
Revises: e52c9a103dc9
Create Date: 2022-11-08 14:20:20.800754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2474a68e112'
down_revision = 'e52c9a103dc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('number_of_questions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'number_of_questions')
    # ### end Alembic commands ###
